apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-resource-report-config
data:
  links.yaml: |
    application:
    - href: "https://kube-web-view.demo.j-serv.de/clusters/local/namespaces/_all/pods?selector=application={id}"
      title: "Search for pods of application {id}"
      icon: search
    ingress:
    - href: "https://kube-web-view.demo.j-serv.de/clusters/local/namespaces/{namespace}/ingresses/{name}"
      title: "View ingress {name} in Kubernetes Web View"
      icon: external-link-alt
    node:
    - href: "https://kube-web-view.demo.j-serv.de/clusters/local/nodes/{name}"
      title: "View node {name} in Kubernetes Web View"
      icon: external-link-alt
    namespace:
    - href: "https://kube-web-view.demo.j-serv.de/clusters/local/namespaces/{name}"
      title: "View namespace {name} in Kubernetes Web View"
      icon: external-link-alt
    pod:
    - href: "https://kube-web-view.demo.j-serv.de/clusters/local/namespaces/{namespace}/pods/{name}"
      title: "View pod {name} in Kubernetes Web View"
      icon: external-link-alt
