apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-web-view
spec:
  template:
    spec:
      initContainers:
      - name: generate-templates
        image: busybox
        command: ["sh", "-c", "mkdir /templates/partials && echo '<footer class=\"footer\"><div class=\"container\"><div class=\"has-text-centered\"><p><a href=\"https://codeberg.org/hjacobs/kube-web-view\">Kubernetes Web View</a> {{ version }}</p><p>This is part of a <a href=\"https://demo.j-serv.de\">public K3s demo</a> setup.</p></div></div></footer>' > /templates/partials/footer.html"]
        volumeMounts:
        - mountPath: /templates
          name: templates

      containers:
      - name: kube-web-view
        args:
        - --port=8080
        - --templates-path=/templates
        - --label-links=application=https://kube-resource-report.demo.j-serv.de/application-{label_value}.html|dollar-sign|Kubernetes Resource Report
        - --default-label-columns=deployments=application;pods=application
        - --preferred-api-versions=deployments=apps/v1
      volumes:
          - name: templates
            emptyDir:
              sizeLimit: 50Mi
