apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ops-view
spec:
  template:
    spec:
      containers:
      - name: service
        args:
        # remove this option to use built-in memory store
        - --redis-url=redis://kube-ops-view-redis:6379
        # example to add external links for nodes and pods
        - --node-link-url-template=https://kube-web-view.demo.j-serv.de/clusters/local/nodes/{name}
        - --pod-link-url-template=https://kube-web-view.demo.j-serv.de/clusters/local/namespaces/{namespace}/pods/{name}
