apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-resource-report
spec:
  template:
    spec:
      containers:
      - name: kube-resource-report
        args:
        - --update-interval-minutes=1
        # Hetzner CX11 is 2.96 EUR/mon
        - --additional-cost-per-cluster=3.29
        - --links-file=/config/links.yaml
        - /output
        volumeMounts:
        - mountPath: /output
          name: report-data
        - name: config-volume
          mountPath: /config
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: report-data
          readOnly: true
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 20Mi
      volumes:
          - name: report-data
            emptyDir:
              sizeLimit: 500Mi
          - name: config-volume
            configMap:
              name: kube-resource-report-config
