apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # default upstream deployments
  - https://codeberg.org/hjacobs/kube-web-view/deploy
  - https://codeberg.org/hjacobs/application-landscape-explorer/deploy
  - https://codeberg.org/hjacobs/kube-downscaler/deploy
  - https://codeberg.org/hjacobs/kube-janitor/deploy
  - https://github.com/hjacobs/kube-ops-view/deploy
  - https://github.com/hjacobs/kube-resource-report/deploy

patchesStrategicMerge:
  # patch container args for demo setup
  - kube-downscaler-deployment.yaml
  - kube-janitor-deployment.yaml
  - kube-janitor-rules-config.yaml
  - kube-ops-view-deployment.yaml
  - kube-resource-report-deployment.yaml
  - kube-web-view-deployment.yaml

resources:
  # add additional resources, e.g. Ingresses
  - application-landscape-explorer-ingress.yaml
  - kube-ops-view-ingress.yaml
  - kube-resource-report-config.yaml
  - kube-resource-report-ingress.yaml
  - kube-web-view-ingress.yaml
  - nginx-deployment.yaml
  - nginx-html.yaml
  - nginx-ingress.yaml
  - nginx-service.yaml
  - traefik-config.yaml
  - traefik-deployment.yaml
  - traefik-pvc.yaml
