apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://codeberg.org/hjacobs/kube-web-view/deploy
  - https://github.com/hjacobs/kube-downscaler/deploy
  - https://github.com/hjacobs/kube-janitor/deploy
  - https://github.com/hjacobs/kube-ops-view/deploy
  - https://github.com/hjacobs/kube-resource-report/deploy

patchesStrategicMerge:
  - kube-ops-view-deployment.yaml
  - kube-ops-view-ingress.yaml
  - kube-resource-report-config.yaml
  - kube-resource-report-deployment.yaml
  - kube-web-view-deployment.yaml

resources:
  - application-landscape-explorer-ingress.yaml
  - folding-at-home.yaml
  - kube-resource-report-ingress.yaml
  - kube-web-view-ingress.yaml
  - nginx-deployment.yaml
  - nginx-html.yaml
  - nginx-ingress.yaml
  - nginx-service.yaml
  - traefik-config.yaml
  - traefik-deployment.yaml
  - traefik-pvc.yaml
