apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    # scale down to 1 replica in the night and on weekends
    downscaler/uptime: "Mon-Fri 07:30-18:00 Europe/Berlin"
    downscaler/downtime-replicas: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-data
          readOnly: true
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 2m
            memory: 20M
      volumes:
      - name: html-data
        configMap:
          name: nginx-html

