apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-local-path-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

